### ISSUE TITLE
invalid use of void

### ISSUE THREAD

**Issue by Poggibonsi1948** [AlphaLima/ESP32-Serial-Bridge#12]
compiling the sketch in Arduino the compiler returns with the following message:

ESP32-Serial-Bridge:101:5: error: invalid use of 'void'
     .onEnd([]() {    <--- here it stops

I have no clue to solve this.
Can anybody show me a way?

**Comment by sdrshnptl** [comment]
I'm pretty much sure you have mistake in syntax.

https://github.com/AlphaLima/ESP32-Serial-Bridge/blob/f6c6ada6aa9a437e4c4a2436d45f98551cd9d6fe/ESP32-Serial-Bridge.ino#L104
