### ISSUE TITLE
Communication lost after couple of hours

### ISSUE THREAD

**Issue by ginodecock** [AlphaLima/ESP32-Serial-Bridge#3]
Hi,

I am using your sketch to remote debug an ESP-32 project.

After a couple of hours it seems that telnet is losing the connection.

Thanks,
Gino

**Comment by AlphaLima** [comment]
Worked for days for me and many other users!
Sonds more like a power/battery problem to me.

**Comment by ginodecock** [comment]
Ok, thanks for the reply.I'll see by adding some more capacitors if it will be more stable. GinoOp 9 mei 2018 21:12 schreef Ulli Heynen <notifications@github.com>:Worked for days for me and many other users!
Sonds more like a power/battery problem to me.

**Comment by AlphaLima** [comment]
???
The ESP32 acts as a access point, it cannot initiate a reconnect, must be done by the client.
Have you tried with another ESP32?

**Comment by ginodecock** [comment]
Hi,It's pretty firmly solderd to the pcb. Cannot replace it. I use the esp as a wifi station connected to wifi access point. Have you checked this way of working over several hours?Thanks, GinoOp 17 mei 2018 20:30 schreef Ulli Heynen <notifications@github.com>:???
The ESP32 acts as a access point, it cannot initiate a reconnect, must be done by the client.
Have you tried with another ESP32?

**Comment by atsteich** [comment]
@ginodecock 
are you using bluetooth? If bluetooth is not defined, the index of buf2 will not be resetted. That could explain why it stops after some time, simply because the buffer is full, and not resetted!

**Comment by AlphaLima** [comment]
Problem solved after bugfix,
