### ISSUE TITLE
pretty mess of code...

### ISSUE THREAD

**Issue by atsteich** [AlphaLima/ESP32-Serial-Bridge#6]
Sorry to say that, but this code is a mess... Just a few things you should definitely change:

1) Don't name the Uart connections "Serial1" and "Serial2", these names are almost always already defined. If you want to setup your own (like you do it) rename them!
2) Udp protocol is only half implemented, finish it, or remove it totally!
3) In config.h you define software serial, but never use it again. Remove it!
4) If Bluetooth is not defined, the index of buffer 2 (what you call i2[num]) will never reset!! This will lead to a fail as soon the buffer is full! If the buffer is full, it should be also printed at least in debug mode to debug com!
5) In station mode, the ssid and password still has to be defined, missing in your header!!
6) Last but not least, i recommend you to use functions! This would make the code way easier to read!!

I have not tried ota, and bluetooth, don't know if these things are working....

**Comment by AlphaLima** [comment]
OK, did a little code clean.

"I have not tried ota, and bluetooth, don't know if these things are working...."
Bluetooth needs a different memorymap!
